# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTCGSCORRECT():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tCGSCORRECT(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1512, 945)
    self.driver.find_element(By.CSS_SELECTOR, "#\\31 > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("Puoi darmi gli smells su questa repo: https://github.com/gianwario/beehave")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
