# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


#Test che va a buon fine
class TestComputetest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_computetest(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1512, 945)
    self.driver.find_element(By.CSS_SELECTOR, ".selected-values").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option:nth-child(37)").click()
    self.driver.find_element(By.ID, "participantsInput").click()
    self.driver.find_element(By.ID, "participantsInput").send_keys("10")
    self.driver.find_element(By.CSS_SELECTOR, ".ok-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(3) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".compute-button").click()
  
